plugin:
  debugging: true #Sends debug messages to the console (development purposes)

mongo:
  host: localhost
  port: 27017
  database: Artex

server:
  name: Lobby
  region: Europe

socials:
  store: "https://store.artex.com"
  website: "https://artex.com"
  discord: "https://discord.gg/eT4B65k5E4"
  youtube: "https://youtube.com/Artex"
  twitter: "https://twitter.com/Artex"
  tiktok: "https://tiktok.com/Artex"
  github: "https://github.com/Cloudy-Development/Artex"
  teamspeak: "ts.artex.com"
  facebook: "facebook.com/Artex"
  instagram: "instagram.com/Artex"

grant:
  default-reason: "No reason specified."

chat-replies:
  enabled: true
  replies:
    reply-1:
      trigger:
        - "hi"
        - "hello"
        - "hey"
      response: "&7&oServer whispers to you: &f&oWhat's up? If you wanna communicate with me, I have to shock you... Because you apparently can't."
    reply-2:
      trigger:
        - "best server"
        - "i love the kb"
        - "great server"
        - "awesome kb"
        - "better than hypixel"
      response: "&7&oServer whispers to you: &f&oIf you wanna make me happy, please buy me a sandwich! &c&o{store} &4&l❤"
    reply-3:
      trigger:
        - "good server"
        - "w server"
        - "nice kb"
        - "better than mmc"
      response: "&7&oServer whispers to you: &f&oWe're glad you're enjoying the server! Consider checking out our ranks at: &c&o{store}"
    reply-4:
      trigger:
        - "bad server"
        - "poor server"
        - "awful server"
        - "shitty kb"
      response: "&7&oServer whispers to you: &f&oSorry to hear that you're not satisfied. We're working on improvements."

spawn:
  join-location: ""

on-join:
  tp-to-spawn: true #Teleports player to spawn on join
  reset-player: true #Resets player's inventory, health, hunger, and effects on join
  welcome-message:
    enabled: true
    # Available placeholders:
    # {player}, {rank}, {color}, {online}, {max}, {store}, {discord}, {website}, {teamspeak},
    # {twitter}, {instagram}, {youtube}, {tiktok}, {facebook}, {github}, {server}, {region}.
    context:
      - " "
      - "&fWelcome to &cArtex Network, &f{color}{player}&c!"
      - " "
      - " &7► &fWebsite: &c{website}"
      - " &7► &fDiscord: &c{discord}"
      - " "
      - " &fYour current Rank is &c{rank}&f, upgrade it now at &c{store}&f."
      - " "

broadcast:
  enabled: true
  send-every: 60
  list:
    message-1:
      - " "
      - "&4&lAnnouncement:"
      - " &fJoin our discord to get informed about news & updates!"
      - "  &7► &c{discord}"
      - " "
    message-2:
      - " "
      - "&4&lAnnouncement:"
      - " &fWatch us on YouTube to have some fun!"
      - "  &7► &c{youtube}"
      - " "
    message-3:
      - " "
      - "&4&lAnnouncement:"
      - " &fDon't forget to check our store for exclusive offers!"
      - "  &7► &c{store}"
      - " "
    message-4:
      - " "
      - "&4&lAnnouncement:"
      - " &fYour current Rank is &c{rank}&f, upgrade it now at:"
      - "  &7► &c{store}"
      - " "
