storage-type: "MONGO" #MONGO or FLAT_FILE
# ------ Mongo Configuration ------
mongo:
  uri: mongodb://localhost:27017
  database: Artex-Core
# ------ Server properties ------
server:
  name: Lobby
  region: Europe
# ------ Messaging format ------
conversation:
  enabled: true # /message and /reply won't register if set to false
  format:
    received: "(From &4{sender}) &c» &f{message}"
    sent: "(To &4{sender}) &a» &f{message}"
# ------ Socials ------
socials:
  store: "https://store.artex.com"
  website: "https://artex.com"
  discord: "https://discord.gg/eT4B65k5E4"
  youtube: "https://youtube.com/Artex"
  twitter: "https://twitter.com/Artex"
  tiktok: "https://tiktok.com/Artex"
  github: "https://github.com/hmEmmy/Artex"
  teamspeak: "ts.artex.com"
  facebook: "facebook.com/Artex"
  instagram: "instagram.com/Artex"
# ------ Default reasons ------
grant:
  default-reason: "No reason specified."
# ------ spawn location of the server ------
spawn:
  join-location: world:0.5:73.0:0.5:90.0:0.0
# ------ configure player join actions ------
on-join:
  tp-to-spawn: false #Teleports player to spawn on join
  reset-player: false #Resets player's inventory, health, hunger, and effects on join
  welcome-message:
    enabled: true
    # Available placeholders:
    # {player}, {rank}, {color}, {online}, {max-online}, {store}, {discord}, {website}, {teamspeak},
    # {twitter}, {instagram}, {youtube}, {tiktok}, {facebook}, {github}, {server}, {region}.
    context:
      - " "
      - "&fWelcome to &4Artex Network, &f{color}{player}&f!"
      - " "
      - " &c► &fWebsite: &4{website}"
      - " &c► &fDiscord: &4{discord}"
      - " &c► &fStore: &4{store}"
      - " "
      - " &fYour current Rank is &c{rank}&f."
      - " "
# ------ Broadcast configuration ------
broadcast:
  enabled: true
  send-every: 60
  list:
    message-1:
      - " "
      - "&7[&4&lArtex&7] &4&lDiscord"
      - " &fJoin our discord to get informed"
      - " &fabout news & updates!"
      - " &c{discord}"
      - " "
    message-2:
      - " "
      - "&7[&4&lArtex&7] &4&lSocial Media"
      - " &fWe now upload shorts on YouTube."
      - " &fCheck them out at"
      - " &c{youtube}&f."
      - " &fDon't forget to like & subscribe!"
      - " "
    message-3:
      - " "
      - "&7[&4&lArtex&7] &4&lStore"
      - " &fDon't forget to check our store"
      - " &ffor exclusive offers at"
      - " &c{store}&f."
      - " "
    message-4:
      - " "
      - "&7[&4&lArtex&7] &4&lStore"
      - " &fNew Tags available at"
      - " &c{store}&f."
      - " &fUse code &cTAGS50 &fto get 50% off!"
      - " "
    message-5:
      - " "
      - "&7[&4&lArtex&7] &4&lStore"
      - " &fWe're currently on a"
      - " &f50% sale on all ranks!"
      - " &fYour one-time opportunity"
      - " &fto get your rank!"
      - " &fVisit our store at"
      - " &c{store}&f."
      - " "